resolver: lts-7.13

packages:
- '.'
- location:
    git: https://github.com/jwaldmann/ersatz.git
    commit: 40dc4c835005924ef1d9eb70db4cd04ad1f19b40
  extra-dep: true

extra-deps: []

flags: {}

extra-package-dbs: []

system-ghc: true
